### ISSUE TITLE
Version errors

### ISSUE THREAD

**Issue by Jaswanth-Devarinti** [nikitalpopov/master#1]
There are module importing errors, even though I installed them according to the requirements.txt. It's not working even in colab as I am getting many errors. Could you please send the updated version of colab file. Thank you.

**Comment by milind-soni** [comment]
> There are module importing errors, even though I installed them according to the requirements.txt. It's not working even in colab as I am getting many errors. Could you please send the updated version of colab file. Thank you.

did you get an alternative?

**Comment by Jaswanth-Devarinti** [comment]
I had to use another git source
